### ISSUE TITLE
Large datasets for EM

### ISSUE THREAD

**Issue by dawsonphan** [lch14forever/BEEM#3]
I have a 60 columns by 1532 rows dataset for inputting into EM. Is this too large for the function to handle? I tried running it for 12 hours and it didn't output anything - would I have to reduce the community size prior to running EM?

**Comment by lch14forever** [comment]
May I know what are the rows and columns? You have 60 samples and 1532 OTUs/taxa?

**Comment by dawsonphan** [comment]
Yes! That is correct.

**Comment by lch14forever** [comment]
I don't think you have enough samples for handling that many taxa... Also, the transformation used in BEEM assumes you have the OTU present in most of the samples. You might want to remove those rare taxa before running it.

**Comment by dawsonphan** [comment]
Oh okay thank you! I tried reducing it to 171 taxa with 60 samples and it has been 1.5 hrs and its still running under iteration 1. Is that normal?

I also got this message:
**The following species are not recommended due to their low/high abudances** - is this what is causing the long computation time?

**Comment by lch14forever** [comment]
The message was for selecting a proper reference for the additive log ratio transformation. Long running time is due to the number of OTUs you have. I think with 60 samples, you might want to reduce your taxa to below 50 (I think ideally 12 taxa)...
